In [2]:
import pandas as pd
import pymongo

df = pd.read_csv('data.csv')
df.head()
df.describe()

,id,Age,Driving_License,Region_Code,Previously_Insured,Annual_Premium,Policy_Sales_Channel,Vintage,Response
count,381109.000000,381109.000000,381109.000000,381109.000000,381109.000000,381109.000000,381109.000000,381109.000000,381109.000000
mean,190555.000000,38.822584,0.997869,26.388807,0.458210,30564.389581,112.034295,154.347397,0.122563
std,110016.836208,15.511611,0.046110,13.229888,0.498251,17213.155057,54.203995,83.671304,0.327936
min,1.000000,20.000000,0.000000,0.000000,0.000000,2630.000000,1.000000,10.000000,0.000000
25%,95278.000000,25.000000,1.000000,15.000000,0.000000,24405.000000,29.000000,82.000000,0.000000
50%,190555.000000,36.000000,1.000000,28.000000,0.000000,31669.000000,133.000000,154.000000,0.000000
75%,285832.000000,49.000000,1.000000,35.000000,1.000000,39400.000000,152.000000,227.000000,0.000000
max,381109.000000,85.000000,1.000000,52.000000,1.000000,540165.000000,163.000000,299.000000,1.000000

In [2]:
# df should be converted into dict before we push it to mongodb

data = df.to_dict(orient='records')
# data

In [ ]:
DB_NAME = "Proj1"
COLLECTION_NAME = "Proj1-Data"

# above, either remove your credentials or delete the mongoDB resource bofore pushing it to github.

In [4]:
client = pymongo.MongoClient(CONNECTION_URL)
data_base = client[DB_NAME]
collection = data_base[COLLECTION_NAME]

In [5]:
# Uploading data to MongoDB
rec = collection.insert_many(data)

In [6]:
# Load back data from mongodb

df = pd.DataFrame(list(collection.find()))
df.head(2)

,_id,id,Gender,Age,Driving_License,Region_Code,Previously_Insured,Vehicle_Age,Vehicle_Damage,Annual_Premium,Policy_Sales_Channel,Vintage,Response
0,69b9498bf0dfd5d9dbad4ac5,1,Male,44,1,28.0,0,> 2 Years,Yes,40454.0,26.0,217,1
1,69b9498bf0dfd5d9dbad4ac6,2,Male,76,1,3.0,0,1-2 Year,No,33536.0,26.0,183,0

In [7]:
## If you are getting timeout issue

# import certifi
# client = pymongo.MongoClient(CONNECTION_URL, tlsCAFile=certifi.where())
# # TO CREATE THE DATABASE
# data_base = client[DB_NAME]
# collection = data_base[COLLECTION_NAME]
# # TO INSERT DATA INTO THE COLLECTION
# rec = collection.insert_many(data)